version: 0.0
os: linux
files:
  - source: /www/
    destination: /var/www/codeversion/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/pregenerate_setup.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root

