version: 0.0
os: linux
files:
  - source: /www/
    destination: /var/www/codeversion/
permissions:
  - object: /var/www/example.com
    pattern: "**"
    owner: www-data
    group: www-data
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/application_stop
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  AfterInstall: 
    - location: scripts/after_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service
      timeout: 300
      runas: root

