version: 0.0
os: linux
files:
  - source: /www/
    destination: /var/www/codeversion/
hooks:
  # BeforeInstall:
  #   - location: scripts/install_dependencies
  #     timeout: 300
  #     runas: root
  BeforeInstall:
    - location: scripts/beforeinstall_setup
      timeout: 300
      runas: root
  AfterInstall: 
    - location: scripts/aferinstall_setup
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/applicationstart_setup
      timeout: 300
      runas: root

