#!/bin/bash

# We keep a history of the releases on this folder
RELEASE_DIR="/var/www/code_release"

# Project folder name
PROJECT_FOLDER="/var/www/html"

#######################################
###### NOT EDIT BEYOND THIS LINE ######
#######################################

# Exporting paths
export PATH=$PATH:/bin:/usr/bin:/usr/local/bin

# Get latest version
VERSION=$(ls ${RELEASE_DIR}/ | tail -n 1)

# Generate Symlink to latest version
rm -rf ${PROJECT_FOLDER}; ln -s ${RELEASE_DIR}/${VERSION} ${PROJECT_FOLDER}

# Check if Apache is running 
isExistApp=$(pgrep httpd)

# Apache is running
if [[ -n  $isExistApp ]]; then
    # Reload Apache in a nice and safely way
    /usr/sbin/httpd -k graceful
else
    # Apache is not running
    systemctl start httpd.service
   
    # Just print debug message
    echo "Apache is not running"
fi