#!/bin/bash

# This is the folder where we copy the code
CODE_VERSION="/var/www/codeversion"

# We keep a history of the releases on this folder
RELEASE_DIR="/var/www/code_release"

#######################################
###### NOT EDIT BEYOND THIS LINE ######
#######################################

# Exporting paths
export PATH=$PATH:/bin:/usr/bin:/usr/local/bin

# Delete previous version in case of code exist
rm -rf ${CODE_VERSION}