#!/bin/bash

# Check if Apache is running 
isExistApp=$(pgrep httpd)

# Apache is running
if [[ -n  $isExistApp ]]; then
    # Reload Apache in a nice and safely 
    /usr/sbin/httpd -k graceful
else
    # Apache is not running
    systemctl start httpd.service
   
    # Just print debug message
    echo "Apache is not running"

   # Exist 
  #exit 5;
fi