#!/bin/bash

# This is the folder where we copy the code
CODE_VERSION="/var/www/codeversion"

# We keep a history of the releases on this folder
RELEASE_DIR="/var/www/code_release"

#######################################
###### NOT EDIT BEYOND THIS LINE ######
#######################################

# Exporting paths
export PATH=$PATH:/bin:/usr/bin:/usr/local/bin

# Check if release dir exist if and cleanup old versions
if [ -d "${RELEASE_DIR}" ]; then
    echo "Folder already exist ${RELEASE_DIR}"

    # Get current version
    VERSION=$(ls ${RELEASE_DIR}/ | tail -n 1)

    # Debug only
    #echo ${VERSION} > /root/test

    # Delete previous release if exist 
    ls -d ${RELEASE_DIR}/* | grep -v ${VERSION} | xargs rm -rf 
fi